# Generated by Django 2.0.13 on 2019-07-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190712_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamiento',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'DISPONIBLE'), ('NO DISPONIBLE', 'NO DISPONIBLE')], default='DISPONIBLE', max_length=80),
        ),
    ]
