# Generated by Django 2.0.13 on 2019-07-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_estacionamiento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tipo',
            field=models.CharField(choices=[('ARRENDATARIO', 'ARRENDATARIO'), ('COMÚN', 'COMÚN')], default='DISPONIBLE', max_length=80),
        ),
    ]
