# Generated by Django 2.0.13 on 2019-07-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_estacionamiento_planta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cod',
        ),
    ]
